
// Objective-C API for talking to the following Go packages
//
//	vnet/client/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Cola_FRAMEWORK_H__
#define __Cola_FRAMEWORK_H__

#include "Cola.objc.h"
#include "Universe.objc.h"

#endif
